### ISSUE TITLE
Doesn't work with yarn install

### ISSUE THREAD

**Issue by stevensacks** [rickharrison/create-react-app-sass#7]
For some reason, this library does not work properly when you use `yarn add --dev` or `yarn install` from a freshly checked out repo where this is in the devDependencies in package.json.

I have to manually call `npm install -D create-react-app-sass` after `yarn install` in order for it to work.

Any ideas why this might be happening?

**Comment by rickharrison** [comment]
What is the error message?

**Comment by stevensacks** [comment]
```
> test-project@0.1.0 start /Users/steven/Dev/test-project
> react-scripts-with-sass start

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-sass ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/steven/.nvm/versions/node/v7.3.0/bin/node" "/Users/steven/.nvm/versions/node/v7.3.0/bin/npm" "run" "start"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! test-project@0.1.0 start: `react-scripts-with-sass start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-project@0.1.0 start script 'react-scripts-with-sass start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts-with-sass start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/steven/Dev/test-project/npm-debug.log
Starting the development server...

Failed to compile.

Error in ./src/index.js
Module not found: ./styles/index.css in /Users/steven/Dev/test-project/src
```

**Comment by stevensacks** [comment]
SCSS is not being compiled into CSS because of this error. 

create-react-app-sass *is* in the node_modules folder after the `yarn install`. It's just not working.

Doing a manual install using `npm install -D create-react-app-sass` fixes the issue from then on. The project can be run with `yarn run start` or `npm start` as long as `c-r-a-s` is reinstalled manually beforehand.

**Comment by Sapmagic** [comment]
Encountered the same issue myself, and running `npm install -D create-react-app-sass` fixed it for me. I wonder what the issue with `yarn` is

**Comment by rickharrison** [comment]
This is now the recommended way to include sass: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc
